// Generated by delombok at Sun Sep 12 22:34:07 CST 2021
package top.naccl.dwz.entity;

/**
 * @Description: 响应结果封装
 * @Author: Naccl
 * @Date: 2021-03-21
 */
public class R {
	private Integer code;
	private String msg;
	private Object data;

	public R(Integer code, String msg) {
		this.code = code;
		this.msg = msg;
	}

	public static R ok(String msg, Object data) {
		return new R(200, msg, data);
	}

	public static R create(Integer code, String msg, Object data) {
		return new R(code, msg, data);
	}

	public static R create(Integer code, String msg) {
		return new R(code, msg);
	}

	@java.lang.SuppressWarnings("all")
	public R(final Integer code, final String msg, final Object data) {
		this.code = code;
		this.msg = msg;
		this.data = data;
	}

	@java.lang.SuppressWarnings("all")
	public R() {
	}

	@java.lang.SuppressWarnings("all")
	public Integer getCode() {
		return this.code;
	}

	@java.lang.SuppressWarnings("all")
	public String getMsg() {
		return this.msg;
	}

	@java.lang.SuppressWarnings("all")
	public Object getData() {
		return this.data;
	}

	@java.lang.SuppressWarnings("all")
	public void setCode(final Integer code) {
		this.code = code;
	}

	@java.lang.SuppressWarnings("all")
	public void setMsg(final String msg) {
		this.msg = msg;
	}

	@java.lang.SuppressWarnings("all")
	public void setData(final Object data) {
		this.data = data;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "R(code=" + this.getCode() + ", msg=" + this.getMsg() + ", data=" + this.getData() + ")";
	}
}
