// Generated by delombok at Sun Sep 12 22:34:07 CST 2021
package top.naccl.dwz.entity;

import java.util.Date;

/**
 * @Description: 长短链接映射
 * @Author: Naccl
 * @Date: 2021-03-22
 */
public class UrlMap {
	private Long id;
	private String surl;//短链接
	private String lurl;//长链接
	private Integer views;//访问次数
	private Date createTime;//创建时间

	public UrlMap(String surl, String lurl) {
		this.surl = surl;
		this.lurl = lurl;
		this.views = 0;
		this.createTime = new Date();
	}

	@java.lang.SuppressWarnings("all")
	public UrlMap() {
	}

	@java.lang.SuppressWarnings("all")
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getSurl() {
		return this.surl;
	}

	@java.lang.SuppressWarnings("all")
	public String getLurl() {
		return this.lurl;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getViews() {
		return this.views;
	}

	@java.lang.SuppressWarnings("all")
	public Date getCreateTime() {
		return this.createTime;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final Long id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setSurl(final String surl) {
		this.surl = surl;
	}

	@java.lang.SuppressWarnings("all")
	public void setLurl(final String lurl) {
		this.lurl = lurl;
	}

	@java.lang.SuppressWarnings("all")
	public void setViews(final Integer views) {
		this.views = views;
	}

	@java.lang.SuppressWarnings("all")
	public void setCreateTime(final Date createTime) {
		this.createTime = createTime;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "UrlMap(id=" + this.getId() + ", surl=" + this.getSurl() + ", lurl=" + this.getLurl() + ", views=" + this.getViews() + ", createTime=" + this.getCreateTime() + ")";
	}
}
